language: python
dist: trusty

python:
  - "3.6"
install:
  pip install -r requirements.txt

script: 
  - make html

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  target-branch: master
  on:
    branch: master
